import sys

with open("client/src/pages/AiAgentsPage.tsx", "r") as f:
    lines = f.readlines()

start = -1
end = -1
for i, line in enumerate(lines):
    if "catch (apiErr)" in line:
        start = i
    if "// Store in Zustand" in line and start != -1:
        end = i
        break

if start != -1 and end != -1:
    new_lines = lines[:start] + [
        "        } catch (apiErr: any) {\n",
        "          console.error(\"Backend API error:\", apiErr);\n",
        "          throw new Error(apiErr.message || \"API connection failed\");\n",
        "        }\n",
        "        if (!debateConversation || debateConversation.length === 0) {\n",
        "          throw new Error(\"No debate generated by backend\");\n",
        "        }\n",
        "        streamDebateLogs(debateConversation);\n",
        "        const avgDelay = 1500 + (debateConversation.length - 1) * (3500 + 500) + 2000;\n",
        "        await new Promise((resolve) => setTimeout(resolve, avgDelay));\n",
        "        setIsLoading(false);\n",
        "        setIsTyping(false);\n",
        "        setActiveSpeakerId(null);\n",
        "        if (!strategyData) throw new Error(\"No strategy data returned from backend\");\n\n"
    ] + lines[end:]
    
    with open("client/src/pages/AiAgentsPage.tsx", "w") as f:
        f.writelines(new_lines)
    print("Success")
else:
    print(f"Failed. Start: {start}, End: {end}")

